//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chrismo.TagMotion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Dokumente und Einstellungen\\chrsm\\Desktop\\DirectLinks")]
        public string SourceDirs {
            get {
                return ((string)(this["SourceDirs"]));
            }
            set {
                this["SourceDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedSourceDir {
            get {
                return ((int)(this["SelectedSourceDir"]));
            }
            set {
                this["SelectedSourceDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\HQ?H:\\Audio?C:\\Dokumente und Einstellungen\\chrsm\\Desktop")]
        public string DestinationDirs {
            get {
                return ((string)(this["DestinationDirs"]));
            }
            set {
                this["DestinationDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedDestinationDir {
            get {
                return ((int)(this["SelectedDestinationDir"]));
            }
            set {
                this["SelectedDestinationDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%RECORDARTIST\\[%YEAR] %RECORDARTIST - %RECORDTITLE\\%TRACK - %ARTIST - %TITLE?[%LA" +
            "BEL]\\[%COMMENT] %RECORDARTIST - %RECORDTITLE\\%TRACK - %ARTIST - %TITLE")]
        public string FileStructures {
            get {
                return ((string)(this["FileStructures"]));
            }
            set {
                this["FileStructures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedFileStructure {
            get {
                return ((int)(this["SelectedFileStructure"]));
            }
            set {
                this["SelectedFileStructure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoTypes {
            get {
                return ((string)(this["InfoTypes"]));
            }
            set {
                this["InfoTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CreationTime")]
        public string SortType {
            get {
                return ((string)(this["SortType"]));
            }
            set {
                this["SortType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreeDBChecking {
            get {
                return ((bool)(this["FreeDBChecking"]));
            }
            set {
                this["FreeDBChecking"] = value;
            }
        }
    }
}
